workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        # imageUri: gcr.io-docker.pkg.dev/health-care-465520/train-registry/distributed:latest
        imageUri: europe-west1-docker.pkg.dev/health-care-465520/train-registry/distributed:latest