version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../dockerfiles/frontend.Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: dockerfiles/api.Dockerfile
    ports:
      - "8000:8000"
