name: API Integration Tests

on:
  push:
    branches: [ main, cloud-run ]
  pull_request:
    branches: [ main, cloud-run ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser" --health-interval=10s --health-timeout=5s --health-retries=5

    env:
      DATABASE_URL: postgresql://testuser:testpass@localhost:5432/testdb

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -r tests/requirements_tests.txt
          pip install pytest

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -U testuser && break
            sleep 2
          done

      - name: Run integration tests
        env:
          PYTHONPATH: .
          DATABASE_URL: postgresql://testuser:testpass@localhost:5432/testdb
        run: |
          source env/bin/activate
          pytest tests/integrationtests --maxfail=3 --disable-warnings -v
