[theme]
primaryColor = "#2563eb"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#e0e7ef"
textColor = "#22223b"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "minimal"
